// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GosuMobileGateway.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#import <Protobuf/GPBProtocolBuffers.h>

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class UserCredential;
@class grpcIAPInit;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - GosuMobileGatewayRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface GosuMobileGatewayRoot : GPBRootObject
@end

#pragma mark - SubcribeEvents_Request

typedef GPB_ENUM(SubcribeEvents_Request_FieldNumber) {
  SubcribeEvents_Request_FieldNumber_Credential = 1,
  SubcribeEvents_Request_FieldNumber_EventName = 2,
  SubcribeEvents_Request_FieldNumber_JsonStringData = 3,
};

/**
 * ======================================================
 * Common Messages
 * ======================================================
 **/
GPB_FINAL @interface SubcribeEvents_Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserCredential *credential;
/** Test to see if @c credential has been set. */
@property(nonatomic, readwrite) BOOL hasCredential;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *eventName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *jsonStringData;

@end

#pragma mark - UserCredential

typedef GPB_ENUM(UserCredential_FieldNumber) {
  UserCredential_FieldNumber_Username = 1,
  UserCredential_FieldNumber_RoleId = 2,
  UserCredential_FieldNumber_AccessToken = 3,
  UserCredential_FieldNumber_ApiKey = 4,
};

GPB_FINAL @interface UserCredential : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite) int32_t roleId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *apiKey;

@end

#pragma mark - Empty_Response

typedef GPB_ENUM(Empty_Response_FieldNumber) {
  Empty_Response_FieldNumber_ReturnCode = 1,
  Empty_Response_FieldNumber_MsgCode = 2,
};

GPB_FINAL @interface Empty_Response : GPBMessage

@property(nonatomic, readwrite) int32_t returnCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgCode;

@end

#pragma mark - String_Response

typedef GPB_ENUM(String_Response_FieldNumber) {
  String_Response_FieldNumber_ReturnCode = 1,
  String_Response_FieldNumber_MsgCode = 2,
  String_Response_FieldNumber_StringValue = 3,
};

GPB_FINAL @interface String_Response : GPBMessage

@property(nonatomic, readwrite) int32_t returnCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgCode;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *stringValue;

@end

#pragma mark - Empty_Request

typedef GPB_ENUM(Empty_Request_FieldNumber) {
  Empty_Request_FieldNumber_Credential = 1,
};

GPB_FINAL @interface Empty_Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserCredential *credential;
/** Test to see if @c credential has been set. */
@property(nonatomic, readwrite) BOOL hasCredential;

@end

#pragma mark - String_Request

typedef GPB_ENUM(String_Request_FieldNumber) {
  String_Request_FieldNumber_Credential = 1,
  String_Request_FieldNumber_StringValue = 2,
};

GPB_FINAL @interface String_Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserCredential *credential;
/** Test to see if @c credential has been set. */
@property(nonatomic, readwrite) BOOL hasCredential;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *stringValue;

@end

#pragma mark - Login_Request

typedef GPB_ENUM(Login_Request_FieldNumber) {
  Login_Request_FieldNumber_Credential = 1,
  Login_Request_FieldNumber_UserName = 2,
  Login_Request_FieldNumber_Password = 3,
  Login_Request_FieldNumber_ClientId = 4,
  Login_Request_FieldNumber_DeviceId = 5,
  Login_Request_FieldNumber_GameId = 6,
  Login_Request_FieldNumber_SdkSignature = 7,
  Login_Request_FieldNumber_SecurityCode = 8,
  Login_Request_FieldNumber_Signature = 9,
  Login_Request_FieldNumber_DeviceBrand = 10,
};

/**
 * ======================================================
 * Messages
 * ======================================================
 **/
GPB_FINAL @interface Login_Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserCredential *credential;
/** Test to see if @c credential has been set. */
@property(nonatomic, readwrite) BOOL hasCredential;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gameId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sdkSignature;

@property(nonatomic, readwrite, copy, null_resettable) NSString *securityCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *signature;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceBrand;

@end

#pragma mark - Login_Response

typedef GPB_ENUM(Login_Response_FieldNumber) {
  Login_Response_FieldNumber_ReturnCode = 1,
  Login_Response_FieldNumber_MsgCode = 2,
  Login_Response_FieldNumber_AccessToken = 3,
};

GPB_FINAL @interface Login_Response : GPBMessage

@property(nonatomic, readwrite) int32_t returnCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgCode;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@end

#pragma mark - Register_Request

typedef GPB_ENUM(Register_Request_FieldNumber) {
  Register_Request_FieldNumber_Credential = 1,
  Register_Request_FieldNumber_OpenIdpartner = 2,
  Register_Request_FieldNumber_UserName = 3,
  Register_Request_FieldNumber_Password = 4,
  Register_Request_FieldNumber_Email = 5,
  Register_Request_FieldNumber_ClientId = 6,
  Register_Request_FieldNumber_DeviceId = 7,
  Register_Request_FieldNumber_GameId = 8,
  Register_Request_FieldNumber_SdkSignature = 9,
  Register_Request_FieldNumber_AccountType = 10,
  Register_Request_FieldNumber_SecurityCode = 11,
  Register_Request_FieldNumber_AppToken = 12,
  Register_Request_FieldNumber_Signature = 13,
  Register_Request_FieldNumber_OpenIdtoken = 14,
  Register_Request_FieldNumber_DeviceBrand = 15,
};

/**
 *
 **/
GPB_FINAL @interface Register_Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserCredential *credential;
/** Test to see if @c credential has been set. */
@property(nonatomic, readwrite) BOOL hasCredential;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *openIdpartner;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gameId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sdkSignature;

@property(nonatomic, readwrite, copy, null_resettable) NSString *accountType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *securityCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *signature;

@property(nonatomic, readwrite, copy, null_resettable) NSString *openIdtoken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceBrand;

@end

#pragma mark - Register_Response

typedef GPB_ENUM(Register_Response_FieldNumber) {
  Register_Response_FieldNumber_ReturnCode = 1,
  Register_Response_FieldNumber_MsgCode = 2,
  Register_Response_FieldNumber_TransactionId = 3,
  Register_Response_FieldNumber_AccessToken = 4,
};

/**
 *
 **/
GPB_FINAL @interface Register_Response : GPBMessage

@property(nonatomic, readwrite) int32_t returnCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgCode;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@end

#pragma mark - ActiveAccount_Request

typedef GPB_ENUM(ActiveAccount_Request_FieldNumber) {
  ActiveAccount_Request_FieldNumber_Credential = 1,
  ActiveAccount_Request_FieldNumber_UserName = 2,
  ActiveAccount_Request_FieldNumber_DeviceId = 3,
  ActiveAccount_Request_FieldNumber_GameId = 4,
  ActiveAccount_Request_FieldNumber_ActiveCode = 5,
  ActiveAccount_Request_FieldNumber_TransactionId = 6,
  ActiveAccount_Request_FieldNumber_ClientId = 7,
  ActiveAccount_Request_FieldNumber_Signature = 8,
  ActiveAccount_Request_FieldNumber_DeviceBrand = 9,
};

/**
 *
 **/
GPB_FINAL @interface ActiveAccount_Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserCredential *credential;
/** Test to see if @c credential has been set. */
@property(nonatomic, readwrite) BOOL hasCredential;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gameId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *activeCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *signature;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceBrand;

@end

#pragma mark - ActiveAccount_Response

typedef GPB_ENUM(ActiveAccount_Response_FieldNumber) {
  ActiveAccount_Response_FieldNumber_ReturnCode = 1,
  ActiveAccount_Response_FieldNumber_MsgCode = 2,
  ActiveAccount_Response_FieldNumber_AccessToken = 3,
};

/**
 *
 **/
GPB_FINAL @interface ActiveAccount_Response : GPBMessage

@property(nonatomic, readwrite) int32_t returnCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgCode;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@end

#pragma mark - Logout_Request

typedef GPB_ENUM(Logout_Request_FieldNumber) {
  Logout_Request_FieldNumber_Credential = 1,
  Logout_Request_FieldNumber_AccessToken = 2,
  Logout_Request_FieldNumber_ClientId = 3,
  Logout_Request_FieldNumber_DeviceId = 4,
  Logout_Request_FieldNumber_UserName = 5,
  Logout_Request_FieldNumber_Signature = 6,
};

/**
 *
 **/
GPB_FINAL @interface Logout_Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserCredential *credential;
/** Test to see if @c credential has been set. */
@property(nonatomic, readwrite) BOOL hasCredential;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *signature;

@end

#pragma mark - LoginByAccessToken_Request

typedef GPB_ENUM(LoginByAccessToken_Request_FieldNumber) {
  LoginByAccessToken_Request_FieldNumber_Credential = 1,
  LoginByAccessToken_Request_FieldNumber_AccessToken = 2,
  LoginByAccessToken_Request_FieldNumber_ClientId = 3,
  LoginByAccessToken_Request_FieldNumber_DeviceId = 4,
  LoginByAccessToken_Request_FieldNumber_UserName = 5,
  LoginByAccessToken_Request_FieldNumber_Signature = 6,
};

GPB_FINAL @interface LoginByAccessToken_Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserCredential *credential;
/** Test to see if @c credential has been set. */
@property(nonatomic, readwrite) BOOL hasCredential;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *signature;

@end

#pragma mark - LoginByAccessToken_Response

typedef GPB_ENUM(LoginByAccessToken_Response_FieldNumber) {
  LoginByAccessToken_Response_FieldNumber_ReturnCode = 1,
  LoginByAccessToken_Response_FieldNumber_MsgCode = 2,
  LoginByAccessToken_Response_FieldNumber_RefreshAccessToken = 3,
};

GPB_FINAL @interface LoginByAccessToken_Response : GPBMessage

@property(nonatomic, readwrite) int32_t returnCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgCode;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *refreshAccessToken;

@end

#pragma mark - LinkAccount_Request

typedef GPB_ENUM(LinkAccount_Request_FieldNumber) {
  LinkAccount_Request_FieldNumber_Credential = 1,
  LinkAccount_Request_FieldNumber_OldAccount = 2,
  LinkAccount_Request_FieldNumber_NewAccount = 3,
  LinkAccount_Request_FieldNumber_Password = 4,
  LinkAccount_Request_FieldNumber_Email = 5,
  LinkAccount_Request_FieldNumber_AccessToken = 6,
  LinkAccount_Request_FieldNumber_GameId = 7,
  LinkAccount_Request_FieldNumber_DeviceId = 8,
  LinkAccount_Request_FieldNumber_ClientId = 9,
  LinkAccount_Request_FieldNumber_Signature = 10,
};

GPB_FINAL @interface LinkAccount_Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserCredential *credential;
/** Test to see if @c credential has been set. */
@property(nonatomic, readwrite) BOOL hasCredential;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *oldAccount;

@property(nonatomic, readwrite, copy, null_resettable) NSString *newAccount NS_RETURNS_NOT_RETAINED;

@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gameId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *signature;

@end

#pragma mark - LinkAccount_Response

typedef GPB_ENUM(LinkAccount_Response_FieldNumber) {
  LinkAccount_Response_FieldNumber_ReturnCode = 1,
  LinkAccount_Response_FieldNumber_MsgCode = 2,
  LinkAccount_Response_FieldNumber_TransactionId = 3,
};

GPB_FINAL @interface LinkAccount_Response : GPBMessage

@property(nonatomic, readwrite) int32_t returnCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgCode;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionId;

@end

#pragma mark - RecoveryPasswordRequest_Request

typedef GPB_ENUM(RecoveryPasswordRequest_Request_FieldNumber) {
  RecoveryPasswordRequest_Request_FieldNumber_Credential = 1,
  RecoveryPasswordRequest_Request_FieldNumber_UserName = 2,
  RecoveryPasswordRequest_Request_FieldNumber_ClientId = 3,
  RecoveryPasswordRequest_Request_FieldNumber_DeviceId = 4,
  RecoveryPasswordRequest_Request_FieldNumber_GameId = 5,
  RecoveryPasswordRequest_Request_FieldNumber_ApkSignature = 6,
  RecoveryPasswordRequest_Request_FieldNumber_NewPassword = 7,
  RecoveryPasswordRequest_Request_FieldNumber_AppToken = 8,
  RecoveryPasswordRequest_Request_FieldNumber_ChangeBy = 9,
  RecoveryPasswordRequest_Request_FieldNumber_Signature = 10,
};

/**
 *
 **/
GPB_FINAL @interface RecoveryPasswordRequest_Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserCredential *credential;
/** Test to see if @c credential has been set. */
@property(nonatomic, readwrite) BOOL hasCredential;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gameId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *apkSignature;

@property(nonatomic, readwrite, copy, null_resettable) NSString *newPassword NS_RETURNS_NOT_RETAINED;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appToken;

@property(nonatomic, readwrite) int32_t changeBy;

@property(nonatomic, readwrite, copy, null_resettable) NSString *signature;

@end

#pragma mark - RecoveryPasswordRequest_Response

typedef GPB_ENUM(RecoveryPasswordRequest_Response_FieldNumber) {
  RecoveryPasswordRequest_Response_FieldNumber_ReturnCode = 1,
  RecoveryPasswordRequest_Response_FieldNumber_MsgCode = 2,
  RecoveryPasswordRequest_Response_FieldNumber_TransactionId = 3,
  RecoveryPasswordRequest_Response_FieldNumber_Otp = 4,
  RecoveryPasswordRequest_Response_FieldNumber_Email = 5,
  RecoveryPasswordRequest_Response_FieldNumber_PhoneNumber = 6,
};

GPB_FINAL @interface RecoveryPasswordRequest_Response : GPBMessage

@property(nonatomic, readwrite) int32_t returnCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgCode;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *otp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite, copy, null_resettable) NSString *phoneNumber;

@end

#pragma mark - RecoveryPasswordSubmit_Request

typedef GPB_ENUM(RecoveryPasswordSubmit_Request_FieldNumber) {
  RecoveryPasswordSubmit_Request_FieldNumber_Credential = 1,
  RecoveryPasswordSubmit_Request_FieldNumber_UserName = 2,
  RecoveryPasswordSubmit_Request_FieldNumber_Otp = 3,
  RecoveryPasswordSubmit_Request_FieldNumber_TransactionId = 4,
  RecoveryPasswordSubmit_Request_FieldNumber_ClientId = 5,
  RecoveryPasswordSubmit_Request_FieldNumber_DeviceId = 6,
  RecoveryPasswordSubmit_Request_FieldNumber_Signature = 7,
};

GPB_FINAL @interface RecoveryPasswordSubmit_Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserCredential *credential;
/** Test to see if @c credential has been set. */
@property(nonatomic, readwrite) BOOL hasCredential;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *otp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *signature;

@end

#pragma mark - OpenGameLog_Request

typedef GPB_ENUM(OpenGameLog_Request_FieldNumber) {
  OpenGameLog_Request_FieldNumber_Credential = 1,
  OpenGameLog_Request_FieldNumber_UserName = 2,
  OpenGameLog_Request_FieldNumber_ClientId = 3,
  OpenGameLog_Request_FieldNumber_SdkVersion = 4,
  OpenGameLog_Request_FieldNumber_DeviceId = 5,
  OpenGameLog_Request_FieldNumber_GameId = 6,
  OpenGameLog_Request_FieldNumber_GameVersion = 7,
  OpenGameLog_Request_FieldNumber_AppToken = 8,
  OpenGameLog_Request_FieldNumber_Platform = 9,
  OpenGameLog_Request_FieldNumber_PlatformVersion = 10,
  OpenGameLog_Request_FieldNumber_DeviceBrand = 11,
  OpenGameLog_Request_FieldNumber_DeviceModel = 12,
  OpenGameLog_Request_FieldNumber_Macaddress = 13,
  OpenGameLog_Request_FieldNumber_ExtraInfo = 14,
  OpenGameLog_Request_FieldNumber_ServerId = 15,
  OpenGameLog_Request_FieldNumber_CharacterId = 16,
  OpenGameLog_Request_FieldNumber_NationalId = 17,
  OpenGameLog_Request_FieldNumber_CustomerId = 18,
  OpenGameLog_Request_FieldNumber_Adsid = 19,
  OpenGameLog_Request_FieldNumber_ExtraInfo1 = 20,
  OpenGameLog_Request_FieldNumber_ExtraInfo2 = 21,
  OpenGameLog_Request_FieldNumber_ExtraInfo3 = 22,
};

/**
 *
 **/
GPB_FINAL @interface OpenGameLog_Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserCredential *credential;
/** Test to see if @c credential has been set. */
@property(nonatomic, readwrite) BOOL hasCredential;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sdkVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gameId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gameVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *platform;

@property(nonatomic, readwrite, copy, null_resettable) NSString *platformVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceBrand;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceModel;

@property(nonatomic, readwrite, copy, null_resettable) NSString *macaddress;

@property(nonatomic, readwrite, copy, null_resettable) NSString *extraInfo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *serverId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *characterId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nationalId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *customerId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *adsid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *extraInfo1;

@property(nonatomic, readwrite, copy, null_resettable) NSString *extraInfo2;

@property(nonatomic, readwrite, copy, null_resettable) NSString *extraInfo3;

@end

#pragma mark - GetProfile_Request

typedef GPB_ENUM(GetProfile_Request_FieldNumber) {
  GetProfile_Request_FieldNumber_Credential = 1,
  GetProfile_Request_FieldNumber_UserName = 2,
  GetProfile_Request_FieldNumber_AccessToken = 3,
  GetProfile_Request_FieldNumber_ClientId = 4,
  GetProfile_Request_FieldNumber_DeviceId = 5,
  GetProfile_Request_FieldNumber_Signature = 6,
};

GPB_FINAL @interface GetProfile_Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserCredential *credential;
/** Test to see if @c credential has been set. */
@property(nonatomic, readwrite) BOOL hasCredential;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *signature;

@end

#pragma mark - GetProfile_Response

typedef GPB_ENUM(GetProfile_Response_FieldNumber) {
  GetProfile_Response_FieldNumber_ReturnCode = 1,
  GetProfile_Response_FieldNumber_MsgCode = 2,
  GetProfile_Response_FieldNumber_IsGuest = 3,
  GetProfile_Response_FieldNumber_IsOpenId = 4,
  GetProfile_Response_FieldNumber_OpenIdpartner = 5,
  GetProfile_Response_FieldNumber_Status = 6,
  GetProfile_Response_FieldNumber_EmailStatus = 7,
  GetProfile_Response_FieldNumber_PhoneStatus = 8,
  GetProfile_Response_FieldNumber_RoleId = 9,
  GetProfile_Response_FieldNumber_CustomerId = 10,
  GetProfile_Response_FieldNumber_UserName = 11,
  GetProfile_Response_FieldNumber_NationalCode = 12,
  GetProfile_Response_FieldNumber_PhoneNumber = 13,
  GetProfile_Response_FieldNumber_Fullname = 14,
  GetProfile_Response_FieldNumber_Email = 15,
  GetProfile_Response_FieldNumber_Address = 16,
  GetProfile_Response_FieldNumber_NumberId = 17,
  GetProfile_Response_FieldNumber_IssueDate = 18,
  GetProfile_Response_FieldNumber_IssuePlace = 19,
  GetProfile_Response_FieldNumber_NationalId = 20,
  GetProfile_Response_FieldNumber_CityId = 21,
  GetProfile_Response_FieldNumber_Birthday = 22,
  GetProfile_Response_FieldNumber_Gender = 23,
};

GPB_FINAL @interface GetProfile_Response : GPBMessage

@property(nonatomic, readwrite) int32_t returnCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgCode;

/** */
@property(nonatomic, readwrite) int32_t isGuest;

@property(nonatomic, readwrite) int32_t isOpenId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *openIdpartner;

@property(nonatomic, readwrite) int32_t status;

@property(nonatomic, readwrite) int32_t emailStatus;

@property(nonatomic, readwrite) int32_t phoneStatus;

@property(nonatomic, readwrite) int32_t roleId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *customerId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nationalCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *phoneNumber;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fullname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;

@property(nonatomic, readwrite, copy, null_resettable) NSString *numberId;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *issueDate;
/** Test to see if @c issueDate has been set. */
@property(nonatomic, readwrite) BOOL hasIssueDate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *issuePlace;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nationalId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *cityId;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *birthday;
/** Test to see if @c birthday has been set. */
@property(nonatomic, readwrite) BOOL hasBirthday;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gender;

@end

#pragma mark - SdkInit_Request

typedef GPB_ENUM(SdkInit_Request_FieldNumber) {
  SdkInit_Request_FieldNumber_Credential = 1,
  SdkInit_Request_FieldNumber_ClientId = 2,
  SdkInit_Request_FieldNumber_DeviceId = 3,
  SdkInit_Request_FieldNumber_SdkSignature = 4,
};

/**
 *
 **/
GPB_FINAL @interface SdkInit_Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserCredential *credential;
/** Test to see if @c credential has been set. */
@property(nonatomic, readwrite) BOOL hasCredential;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sdkSignature;

@end

#pragma mark - SdkInit_Response

typedef GPB_ENUM(SdkInit_Response_FieldNumber) {
  SdkInit_Response_FieldNumber_ReturnCode = 1,
  SdkInit_Response_FieldNumber_MsgCode = 2,
  SdkInit_Response_FieldNumber_InitData = 3,
};

GPB_FINAL @interface SdkInit_Response : GPBMessage

@property(nonatomic, readwrite) int32_t returnCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgCode;

/**
 *
 * bool IsNeedInstallLog = 3;
 * string Data = 3;
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *initData;
- (NSString *)initData GPB_METHOD_FAMILY_NONE;

@end

#pragma mark - IAPInit_Request

typedef GPB_ENUM(IAPInit_Request_FieldNumber) {
  IAPInit_Request_FieldNumber_Credential = 1,
  IAPInit_Request_FieldNumber_ClientId = 2,
  IAPInit_Request_FieldNumber_UserName = 3,
  IAPInit_Request_FieldNumber_CustomerId = 4,
  IAPInit_Request_FieldNumber_NationalId = 5,
  IAPInit_Request_FieldNumber_CharacterId = 6,
  IAPInit_Request_FieldNumber_GameId = 7,
  IAPInit_Request_FieldNumber_ServerId = 8,
  IAPInit_Request_FieldNumber_CurrencyUnit = 9,
  IAPInit_Request_FieldNumber_ChannelId = 10,
  IAPInit_Request_FieldNumber_PackageName = 11,
  IAPInit_Request_FieldNumber_ProductId = 12,
  IAPInit_Request_FieldNumber_ProductName = 13,
  IAPInit_Request_FieldNumber_Amount = 14,
  IAPInit_Request_FieldNumber_Platform = 15,
  IAPInit_Request_FieldNumber_ExtraInfo = 16,
  IAPInit_Request_FieldNumber_Signature = 17,
  IAPInit_Request_FieldNumber_AccessToken = 18,
  IAPInit_Request_FieldNumber_DeviceId = 19,
  IAPInit_Request_FieldNumber_PartnerId = 20,
  IAPInit_Request_FieldNumber_OrderId = 21,
};

GPB_FINAL @interface IAPInit_Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserCredential *credential;
/** Test to see if @c credential has been set. */
@property(nonatomic, readwrite) BOOL hasCredential;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *customerId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nationalId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *characterId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gameId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *serverId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *currencyUnit;

@property(nonatomic, readwrite, copy, null_resettable) NSString *channelId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *packageName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *productId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *productName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *amount;

@property(nonatomic, readwrite, copy, null_resettable) NSString *platform;

@property(nonatomic, readwrite, copy, null_resettable) NSString *extraInfo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *signature;

@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *partnerId;

/** mã đơn hàng phía đối tác */
@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@end

#pragma mark - IAPInit_Response

typedef GPB_ENUM(IAPInit_Response_FieldNumber) {
  IAPInit_Response_FieldNumber_ReturnCode = 1,
  IAPInit_Response_FieldNumber_MsgCode = 2,
  IAPInit_Response_FieldNumber_InitDataArray = 3,
};

GPB_FINAL @interface IAPInit_Response : GPBMessage

@property(nonatomic, readwrite) int32_t returnCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgCode;

/** */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<grpcIAPInit*> *initDataArray;
/** The number of items in @c initDataArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger initDataArray_Count;
- (NSMutableArray<grpcIAPInit*> *)initDataArray GPB_METHOD_FAMILY_NONE;

@end

#pragma mark - grpcIAPInit

typedef GPB_ENUM(grpcIAPInit_FieldNumber) {
  grpcIAPInit_FieldNumber_TransactionId = 1,
  grpcIAPInit_FieldNumber_A = 2,
  grpcIAPInit_FieldNumber_B = 3,
  grpcIAPInit_FieldNumber_H = 4,
  grpcIAPInit_FieldNumber_M = 5,
  grpcIAPInit_FieldNumber_S = 6,
  grpcIAPInit_FieldNumber_T = 7,
};

/**
 *
 **/
GPB_FINAL @interface grpcIAPInit : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionId;

@property(nonatomic, readwrite) double a;

@property(nonatomic, readwrite) double b;

@property(nonatomic, readwrite, copy, null_resettable) NSString *h;

@property(nonatomic, readwrite, copy, null_resettable) NSString *m;

@property(nonatomic, readwrite) int32_t s;

@property(nonatomic, readwrite, copy, null_resettable) NSString *t;

@end

#pragma mark - FinalizeIAP_Request

typedef GPB_ENUM(FinalizeIAP_Request_FieldNumber) {
  FinalizeIAP_Request_FieldNumber_Credential = 1,
  FinalizeIAP_Request_FieldNumber_UserName = 2,
  FinalizeIAP_Request_FieldNumber_ClientId = 3,
  FinalizeIAP_Request_FieldNumber_OrderId = 4,
  FinalizeIAP_Request_FieldNumber_OrderToken = 5,
  FinalizeIAP_Request_FieldNumber_ServiceEmail = 6,
  FinalizeIAP_Request_FieldNumber_ExtraInfo = 7,
  FinalizeIAP_Request_FieldNumber_ResultCode = 8,
  FinalizeIAP_Request_FieldNumber_ErrorMessage = 9,
  FinalizeIAP_Request_FieldNumber_Signature = 10,
  FinalizeIAP_Request_FieldNumber_AccessToken = 11,
  FinalizeIAP_Request_FieldNumber_DeviceId = 12,
  FinalizeIAP_Request_FieldNumber_TransactionId = 13,
};

GPB_FINAL @interface FinalizeIAP_Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserCredential *credential;
/** Test to see if @c credential has been set. */
@property(nonatomic, readwrite) BOOL hasCredential;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *serviceEmail;

@property(nonatomic, readwrite, copy, null_resettable) NSString *extraInfo;

@property(nonatomic, readwrite) int32_t resultCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

@property(nonatomic, readwrite, copy, null_resettable) NSString *signature;

@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionId;

@end

#pragma mark - InstallGameLog_Request

typedef GPB_ENUM(InstallGameLog_Request_FieldNumber) {
  InstallGameLog_Request_FieldNumber_Credential = 1,
  InstallGameLog_Request_FieldNumber_Id_p = 2,
  InstallGameLog_Request_FieldNumber_ClientId = 4,
  InstallGameLog_Request_FieldNumber_DeviceId = 5,
  InstallGameLog_Request_FieldNumber_SdkVersion = 6,
  InstallGameLog_Request_FieldNumber_GameId = 7,
  InstallGameLog_Request_FieldNumber_GameVersion = 8,
  InstallGameLog_Request_FieldNumber_Platform = 9,
  InstallGameLog_Request_FieldNumber_DeviceBrand = 10,
  InstallGameLog_Request_FieldNumber_DeviceModel = 11,
  InstallGameLog_Request_FieldNumber_Macaddress = 12,
  InstallGameLog_Request_FieldNumber_Ip = 13,
  InstallGameLog_Request_FieldNumber_NationalId = 14,
  InstallGameLog_Request_FieldNumber_Adsid = 15,
  InstallGameLog_Request_FieldNumber_ExtraInfo1 = 16,
  InstallGameLog_Request_FieldNumber_ExtraInfo2 = 17,
  InstallGameLog_Request_FieldNumber_ExtraInfo3 = 18,
};

/**
 *
 **/
GPB_FINAL @interface InstallGameLog_Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserCredential *credential;
/** Test to see if @c credential has been set. */
@property(nonatomic, readwrite) BOOL hasCredential;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sdkVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gameId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gameVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *platform;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceBrand;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceModel;

@property(nonatomic, readwrite, copy, null_resettable) NSString *macaddress;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ip;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nationalId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *adsid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *extraInfo1;

@property(nonatomic, readwrite, copy, null_resettable) NSString *extraInfo2;

@property(nonatomic, readwrite, copy, null_resettable) NSString *extraInfo3;

@end

#pragma mark - ResendOTP_Request

typedef GPB_ENUM(ResendOTP_Request_FieldNumber) {
  ResendOTP_Request_FieldNumber_Credential = 1,
  ResendOTP_Request_FieldNumber_UserName = 2,
  ResendOTP_Request_FieldNumber_TransactionId = 3,
  ResendOTP_Request_FieldNumber_GameId = 4,
  ResendOTP_Request_FieldNumber_DeviceId = 5,
  ResendOTP_Request_FieldNumber_ContentFlag = 6,
  ResendOTP_Request_FieldNumber_AppToken = 7,
  ResendOTP_Request_FieldNumber_ChangeBy = 8,
  ResendOTP_Request_FieldNumber_ClientId = 9,
  ResendOTP_Request_FieldNumber_Signature = 10,
};

GPB_FINAL @interface ResendOTP_Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserCredential *credential;
/** Test to see if @c credential has been set. */
@property(nonatomic, readwrite) BOOL hasCredential;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gameId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *contentFlag;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appToken;

@property(nonatomic, readwrite) int32_t changeBy;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *signature;

@end

#pragma mark - ResendOTP_Response

typedef GPB_ENUM(ResendOTP_Response_FieldNumber) {
  ResendOTP_Response_FieldNumber_ReturnCode = 1,
  ResendOTP_Response_FieldNumber_MsgCode = 2,
  ResendOTP_Response_FieldNumber_Email = 3,
  ResendOTP_Response_FieldNumber_PhoneNumber = 4,
  ResendOTP_Response_FieldNumber_ContentFlag = 5,
};

/**
 *
 **/
GPB_FINAL @interface ResendOTP_Response : GPBMessage

@property(nonatomic, readwrite) int32_t returnCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgCode;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite, copy, null_resettable) NSString *phoneNumber;

@property(nonatomic, readwrite, copy, null_resettable) NSString *contentFlag;

@end

#pragma mark - RequestActive_Request

typedef GPB_ENUM(RequestActive_Request_FieldNumber) {
  RequestActive_Request_FieldNumber_Credential = 1,
  RequestActive_Request_FieldNumber_UserName = 2,
  RequestActive_Request_FieldNumber_ClientId = 3,
  RequestActive_Request_FieldNumber_ContentFlag = 4,
  RequestActive_Request_FieldNumber_AppToken = 5,
  RequestActive_Request_FieldNumber_ChangeBy = 6,
  RequestActive_Request_FieldNumber_Email = 7,
  RequestActive_Request_FieldNumber_PhoneNumber = 8,
  RequestActive_Request_FieldNumber_Signature = 9,
};

/**
 *
 *
 **/
GPB_FINAL @interface RequestActive_Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserCredential *credential;
/** Test to see if @c credential has been set. */
@property(nonatomic, readwrite) BOOL hasCredential;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *contentFlag;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appToken;

@property(nonatomic, readwrite) int32_t changeBy;

@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite, copy, null_resettable) NSString *phoneNumber;

@property(nonatomic, readwrite, copy, null_resettable) NSString *signature;

@end

#pragma mark - RequestActive_Response

typedef GPB_ENUM(RequestActive_Response_FieldNumber) {
  RequestActive_Response_FieldNumber_ReturnCode = 1,
  RequestActive_Response_FieldNumber_MsgCode = 2,
  RequestActive_Response_FieldNumber_ContentFlag = 3,
  RequestActive_Response_FieldNumber_Email = 4,
  RequestActive_Response_FieldNumber_PhoneNumber = 5,
  RequestActive_Response_FieldNumber_TransactionId = 6,
};

GPB_FINAL @interface RequestActive_Response : GPBMessage

@property(nonatomic, readwrite) int32_t returnCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgCode;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *contentFlag;

@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite, copy, null_resettable) NSString *phoneNumber;

@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionId;

@end

#pragma mark - DeleteAccount_Request

typedef GPB_ENUM(DeleteAccount_Request_FieldNumber) {
  DeleteAccount_Request_FieldNumber_Credential = 1,
  DeleteAccount_Request_FieldNumber_AccessToken = 2,
  DeleteAccount_Request_FieldNumber_ClientId = 3,
  DeleteAccount_Request_FieldNumber_UserName = 4,
  DeleteAccount_Request_FieldNumber_Signature = 5,
};

/**
 *
 **/
GPB_FINAL @interface DeleteAccount_Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserCredential *credential;
/** Test to see if @c credential has been set. */
@property(nonatomic, readwrite) BOOL hasCredential;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *signature;

@end

#pragma mark - ShowInfoGuestAccount_Request

typedef GPB_ENUM(ShowInfoGuestAccount_Request_FieldNumber) {
  ShowInfoGuestAccount_Request_FieldNumber_Credential = 1,
  ShowInfoGuestAccount_Request_FieldNumber_UserName = 2,
  ShowInfoGuestAccount_Request_FieldNumber_AccessToken = 3,
  ShowInfoGuestAccount_Request_FieldNumber_ClientId = 4,
  ShowInfoGuestAccount_Request_FieldNumber_Signature = 5,
};

/**
 *
 **/
GPB_FINAL @interface ShowInfoGuestAccount_Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserCredential *credential;
/** Test to see if @c credential has been set. */
@property(nonatomic, readwrite) BOOL hasCredential;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *signature;

@end

#pragma mark - ShowInfoGuestAccount_Response

typedef GPB_ENUM(ShowInfoGuestAccount_Response_FieldNumber) {
  ShowInfoGuestAccount_Response_FieldNumber_ReturnCode = 1,
  ShowInfoGuestAccount_Response_FieldNumber_MsgCode = 2,
  ShowInfoGuestAccount_Response_FieldNumber_UserName = 3,
  ShowInfoGuestAccount_Response_FieldNumber_Password = 4,
};

GPB_FINAL @interface ShowInfoGuestAccount_Response : GPBMessage

@property(nonatomic, readwrite) int32_t returnCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgCode;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

@end

#pragma mark - CatchLogSDK_Request

typedef GPB_ENUM(CatchLogSDK_Request_FieldNumber) {
  CatchLogSDK_Request_FieldNumber_Credential = 1,
  CatchLogSDK_Request_FieldNumber_ClientId = 2,
  CatchLogSDK_Request_FieldNumber_ActiveKey = 3,
  CatchLogSDK_Request_FieldNumber_Data_p = 4,
  CatchLogSDK_Request_FieldNumber_UserName = 5,
};

/**
 *
 **/
GPB_FINAL @interface CatchLogSDK_Request : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UserCredential *credential;
/** Test to see if @c credential has been set. */
@property(nonatomic, readwrite) BOOL hasCredential;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *activeKey;

@property(nonatomic, readwrite, copy, null_resettable) NSString *data_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
