// Code generated by gRPC proto compiler.  DO NOT EDIT!
// source: GosuMobileGateway.proto

#import <Foundation/Foundation.h>

#if !defined(GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO) || !GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO
#import "GosuMobileGateway.pbobjc.h"
#endif

#if !defined(GPB_GRPC_PROTOCOL_ONLY) || !GPB_GRPC_PROTOCOL_ONLY
#import <ProtoRPC/ProtoService.h>
#import <ProtoRPC/ProtoRPCLegacy.h>
#import <RxLibrary/GRXWriteable.h>
#import <RxLibrary/GRXWriter.h>
#endif

@class ActiveAccount_Request;
@class ActiveAccount_Response;
@class CatchLogSDK_Request;
@class DeleteAccount_Request;
@class Empty_Request;
@class Empty_Response;
@class FinalizeIAP_Request;
@class GetProfile_Request;
@class GetProfile_Response;
@class IAPInit_Request;
@class IAPInit_Response;
@class InstallGameLog_Request;
@class LinkAccount_Request;
@class LinkAccount_Response;
@class LoginByAccessToken_Request;
@class LoginByAccessToken_Response;
@class Login_Request;
@class Login_Response;
@class Logout_Request;
@class OpenGameLog_Request;
@class RecoveryPasswordRequest_Request;
@class RecoveryPasswordRequest_Response;
@class RecoveryPasswordSubmit_Request;
@class Register_Request;
@class Register_Response;
@class RequestActive_Request;
@class RequestActive_Response;
@class ResendOTP_Request;
@class ResendOTP_Response;
@class SdkInit_Request;
@class SdkInit_Response;
@class ShowInfoGuestAccount_Request;
@class ShowInfoGuestAccount_Response;
@class String_Response;
@class SubcribeEvents_Request;

#if !defined(GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO) || !GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO
#import <Protobuf/GPBTimestamp.pbobjc.h>
#endif

@class GRPCUnaryProtoCall;
@class GRPCStreamingProtoCall;
@class GRPCCallOptions;
@protocol GRPCProtoResponseHandler;
@class GRPCProtoCall;


NS_ASSUME_NONNULL_BEGIN

@protocol grpcMobileGatewayService2 <NSObject>

#pragma mark HealthCheck(Empty_Request) returns (String_Response)

/**
 * Health check
 */
- (GRPCUnaryProtoCall *)healthCheckWithMessage:(Empty_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark SubcribeEvents(SubcribeEvents_Request) returns (Empty_Response)

/**
 * For refresh: config, caching,..
 */
- (GRPCUnaryProtoCall *)subcribeEventsWithMessage:(SubcribeEvents_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark Register(Register_Request) returns (Register_Response)

/**
 * 
 */
- (GRPCUnaryProtoCall *)registerWithMessage:(Register_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark ActiveAccount(ActiveAccount_Request) returns (ActiveAccount_Response)

/**
 * 
 */
- (GRPCUnaryProtoCall *)activeAccountWithMessage:(ActiveAccount_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark Login(Login_Request) returns (Login_Response)

- (GRPCUnaryProtoCall *)loginWithMessage:(Login_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark Logout(Logout_Request) returns (Empty_Response)

- (GRPCUnaryProtoCall *)logoutWithMessage:(Logout_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark LoginByAccessToken(LoginByAccessToken_Request) returns (LoginByAccessToken_Response)

- (GRPCUnaryProtoCall *)loginByAccessTokenWithMessage:(LoginByAccessToken_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark LinkAccount(LinkAccount_Request) returns (LinkAccount_Response)

- (GRPCUnaryProtoCall *)linkAccountWithMessage:(LinkAccount_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark RecoveryPasswordRequest(RecoveryPasswordRequest_Request) returns (RecoveryPasswordRequest_Response)

- (GRPCUnaryProtoCall *)recoveryPasswordRequestWithMessage:(RecoveryPasswordRequest_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark RecoveryPasswordSubmit(RecoveryPasswordSubmit_Request) returns (Empty_Response)

- (GRPCUnaryProtoCall *)recoveryPasswordSubmitWithMessage:(RecoveryPasswordSubmit_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark OpenGameLog(OpenGameLog_Request) returns (Empty_Response)

- (GRPCUnaryProtoCall *)openGameLogWithMessage:(OpenGameLog_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark InstallGameLog(InstallGameLog_Request) returns (Empty_Response)

- (GRPCUnaryProtoCall *)installGameLogWithMessage:(InstallGameLog_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark GetProfile(GetProfile_Request) returns (GetProfile_Response)

- (GRPCUnaryProtoCall *)getProfileWithMessage:(GetProfile_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark SdkInit(SdkInit_Request) returns (SdkInit_Response)

/**
 * rpc ResendOTP (ResendOTP_Request)returns (Empty_Response);
 */
- (GRPCUnaryProtoCall *)sdkInitWithMessage:(SdkInit_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark ResendOTP(ResendOTP_Request) returns (ResendOTP_Response)

- (GRPCUnaryProtoCall *)resendOTPWithMessage:(ResendOTP_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark RequestActive(RequestActive_Request) returns (RequestActive_Response)

- (GRPCUnaryProtoCall *)requestActiveWithMessage:(RequestActive_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark IAPInit(IAPInit_Request) returns (IAPInit_Response)

/**
 * 
 */
- (GRPCUnaryProtoCall *)iAPInitWithMessage:(IAPInit_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark FinalizeIAP(FinalizeIAP_Request) returns (Empty_Response)

- (GRPCUnaryProtoCall *)finalizeIAPWithMessage:(FinalizeIAP_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark DeleteAccount(DeleteAccount_Request) returns (Empty_Response)

/**
 * 
 */
- (GRPCUnaryProtoCall *)deleteAccountWithMessage:(DeleteAccount_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark ShowInfoGuestAccount(ShowInfoGuestAccount_Request) returns (ShowInfoGuestAccount_Response)

/**
 * 
 */
- (GRPCUnaryProtoCall *)showInfoGuestAccountWithMessage:(ShowInfoGuestAccount_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark CatchLogSDK(CatchLogSDK_Request) returns (Empty_Response)

/**
 * 
 */
- (GRPCUnaryProtoCall *)catchLogSDKWithMessage:(CatchLogSDK_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

@end

/**
 * The methods in this protocol belong to a set of old APIs that have been deprecated. They do not
 * recognize call options provided in the initializer. Using the v2 protocol is recommended.
 */
@protocol grpcMobileGatewayService <NSObject>

#pragma mark HealthCheck(Empty_Request) returns (String_Response)

/**
 * Health check
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)healthCheckWithRequest:(Empty_Request *)request handler:(void(^)(String_Response *_Nullable response, NSError *_Nullable error))handler;

/**
 * Health check
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToHealthCheckWithRequest:(Empty_Request *)request handler:(void(^)(String_Response *_Nullable response, NSError *_Nullable error))handler;


#pragma mark SubcribeEvents(SubcribeEvents_Request) returns (Empty_Response)

/**
 * For refresh: config, caching,..
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)subcribeEventsWithRequest:(SubcribeEvents_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler;

/**
 * For refresh: config, caching,..
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToSubcribeEventsWithRequest:(SubcribeEvents_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler;


#pragma mark Register(Register_Request) returns (Register_Response)

/**
 * 
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)registerWithRequest:(Register_Request *)request handler:(void(^)(Register_Response *_Nullable response, NSError *_Nullable error))handler;

/**
 * 
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToRegisterWithRequest:(Register_Request *)request handler:(void(^)(Register_Response *_Nullable response, NSError *_Nullable error))handler;


#pragma mark ActiveAccount(ActiveAccount_Request) returns (ActiveAccount_Response)

/**
 * 
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)activeAccountWithRequest:(ActiveAccount_Request *)request handler:(void(^)(ActiveAccount_Response *_Nullable response, NSError *_Nullable error))handler;

/**
 * 
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToActiveAccountWithRequest:(ActiveAccount_Request *)request handler:(void(^)(ActiveAccount_Response *_Nullable response, NSError *_Nullable error))handler;


#pragma mark Login(Login_Request) returns (Login_Response)

- (void)loginWithRequest:(Login_Request *)request handler:(void(^)(Login_Response *_Nullable response, NSError *_Nullable error))handler;

- (GRPCProtoCall *)RPCToLoginWithRequest:(Login_Request *)request handler:(void(^)(Login_Response *_Nullable response, NSError *_Nullable error))handler;


#pragma mark Logout(Logout_Request) returns (Empty_Response)

- (void)logoutWithRequest:(Logout_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler;

- (GRPCProtoCall *)RPCToLogoutWithRequest:(Logout_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler;


#pragma mark LoginByAccessToken(LoginByAccessToken_Request) returns (LoginByAccessToken_Response)

- (void)loginByAccessTokenWithRequest:(LoginByAccessToken_Request *)request handler:(void(^)(LoginByAccessToken_Response *_Nullable response, NSError *_Nullable error))handler;

- (GRPCProtoCall *)RPCToLoginByAccessTokenWithRequest:(LoginByAccessToken_Request *)request handler:(void(^)(LoginByAccessToken_Response *_Nullable response, NSError *_Nullable error))handler;


#pragma mark LinkAccount(LinkAccount_Request) returns (LinkAccount_Response)

- (void)linkAccountWithRequest:(LinkAccount_Request *)request handler:(void(^)(LinkAccount_Response *_Nullable response, NSError *_Nullable error))handler;

- (GRPCProtoCall *)RPCToLinkAccountWithRequest:(LinkAccount_Request *)request handler:(void(^)(LinkAccount_Response *_Nullable response, NSError *_Nullable error))handler;


#pragma mark RecoveryPasswordRequest(RecoveryPasswordRequest_Request) returns (RecoveryPasswordRequest_Response)

- (void)recoveryPasswordRequestWithRequest:(RecoveryPasswordRequest_Request *)request handler:(void(^)(RecoveryPasswordRequest_Response *_Nullable response, NSError *_Nullable error))handler;

- (GRPCProtoCall *)RPCToRecoveryPasswordRequestWithRequest:(RecoveryPasswordRequest_Request *)request handler:(void(^)(RecoveryPasswordRequest_Response *_Nullable response, NSError *_Nullable error))handler;


#pragma mark RecoveryPasswordSubmit(RecoveryPasswordSubmit_Request) returns (Empty_Response)

- (void)recoveryPasswordSubmitWithRequest:(RecoveryPasswordSubmit_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler;

- (GRPCProtoCall *)RPCToRecoveryPasswordSubmitWithRequest:(RecoveryPasswordSubmit_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler;


#pragma mark OpenGameLog(OpenGameLog_Request) returns (Empty_Response)

- (void)openGameLogWithRequest:(OpenGameLog_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler;

- (GRPCProtoCall *)RPCToOpenGameLogWithRequest:(OpenGameLog_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler;


#pragma mark InstallGameLog(InstallGameLog_Request) returns (Empty_Response)

- (void)installGameLogWithRequest:(InstallGameLog_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler;

- (GRPCProtoCall *)RPCToInstallGameLogWithRequest:(InstallGameLog_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler;


#pragma mark GetProfile(GetProfile_Request) returns (GetProfile_Response)

- (void)getProfileWithRequest:(GetProfile_Request *)request handler:(void(^)(GetProfile_Response *_Nullable response, NSError *_Nullable error))handler;

- (GRPCProtoCall *)RPCToGetProfileWithRequest:(GetProfile_Request *)request handler:(void(^)(GetProfile_Response *_Nullable response, NSError *_Nullable error))handler;


#pragma mark SdkInit(SdkInit_Request) returns (SdkInit_Response)

/**
 * rpc ResendOTP (ResendOTP_Request)returns (Empty_Response);
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)sdkInitWithRequest:(SdkInit_Request *)request handler:(void(^)(SdkInit_Response *_Nullable response, NSError *_Nullable error))handler;

/**
 * rpc ResendOTP (ResendOTP_Request)returns (Empty_Response);
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToSdkInitWithRequest:(SdkInit_Request *)request handler:(void(^)(SdkInit_Response *_Nullable response, NSError *_Nullable error))handler;


#pragma mark ResendOTP(ResendOTP_Request) returns (ResendOTP_Response)

- (void)resendOTPWithRequest:(ResendOTP_Request *)request handler:(void(^)(ResendOTP_Response *_Nullable response, NSError *_Nullable error))handler;

- (GRPCProtoCall *)RPCToResendOTPWithRequest:(ResendOTP_Request *)request handler:(void(^)(ResendOTP_Response *_Nullable response, NSError *_Nullable error))handler;


#pragma mark RequestActive(RequestActive_Request) returns (RequestActive_Response)

- (void)requestActiveWithRequest:(RequestActive_Request *)request handler:(void(^)(RequestActive_Response *_Nullable response, NSError *_Nullable error))handler;

- (GRPCProtoCall *)RPCToRequestActiveWithRequest:(RequestActive_Request *)request handler:(void(^)(RequestActive_Response *_Nullable response, NSError *_Nullable error))handler;


#pragma mark IAPInit(IAPInit_Request) returns (IAPInit_Response)

/**
 * 
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)iAPInitWithRequest:(IAPInit_Request *)request handler:(void(^)(IAPInit_Response *_Nullable response, NSError *_Nullable error))handler;

/**
 * 
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToIAPInitWithRequest:(IAPInit_Request *)request handler:(void(^)(IAPInit_Response *_Nullable response, NSError *_Nullable error))handler;


#pragma mark FinalizeIAP(FinalizeIAP_Request) returns (Empty_Response)

- (void)finalizeIAPWithRequest:(FinalizeIAP_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler;

- (GRPCProtoCall *)RPCToFinalizeIAPWithRequest:(FinalizeIAP_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler;


#pragma mark DeleteAccount(DeleteAccount_Request) returns (Empty_Response)

/**
 * 
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)deleteAccountWithRequest:(DeleteAccount_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler;

/**
 * 
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToDeleteAccountWithRequest:(DeleteAccount_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler;


#pragma mark ShowInfoGuestAccount(ShowInfoGuestAccount_Request) returns (ShowInfoGuestAccount_Response)

/**
 * 
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)showInfoGuestAccountWithRequest:(ShowInfoGuestAccount_Request *)request handler:(void(^)(ShowInfoGuestAccount_Response *_Nullable response, NSError *_Nullable error))handler;

/**
 * 
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToShowInfoGuestAccountWithRequest:(ShowInfoGuestAccount_Request *)request handler:(void(^)(ShowInfoGuestAccount_Response *_Nullable response, NSError *_Nullable error))handler;


#pragma mark CatchLogSDK(CatchLogSDK_Request) returns (Empty_Response)

/**
 * 
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)catchLogSDKWithRequest:(CatchLogSDK_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler;

/**
 * 
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToCatchLogSDKWithRequest:(CatchLogSDK_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler;


@end


#if !defined(GPB_GRPC_PROTOCOL_ONLY) || !GPB_GRPC_PROTOCOL_ONLY
/**
 * Basic service implementation, over gRPC, that only does
 * marshalling and parsing.
 */
@interface grpcMobileGatewayService : GRPCProtoService<grpcMobileGatewayService2, grpcMobileGatewayService>
- (instancetype)initWithHost:(NSString *)host callOptions:(GRPCCallOptions *_Nullable)callOptions NS_DESIGNATED_INITIALIZER;
+ (instancetype)serviceWithHost:(NSString *)host callOptions:(GRPCCallOptions *_Nullable)callOptions;
// The following methods belong to a set of old APIs that have been deprecated.
- (instancetype)initWithHost:(NSString *)host;
+ (instancetype)serviceWithHost:(NSString *)host;
@end
#endif

NS_ASSUME_NONNULL_END

