// Code generated by gRPC proto compiler.  DO NOT EDIT!
// source: MobileGateway.proto

#if !defined(GPB_GRPC_PROTOCOL_ONLY) || !GPB_GRPC_PROTOCOL_ONLY
#import "MobileGateway.pbrpc.h"
#import "MobileGateway.pbobjc.h"
#import <ProtoRPC/ProtoRPCLegacy.h>
#import <RxLibrary/GRXWriter+Immediate.h>

#import <Protobuf/GPBTimestamp.pbobjc.h>

@implementation grpcMobileGatewayService

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wobjc-designated-initializers"

// Designated initializer
- (instancetype)initWithHost:(NSString *)host callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [super initWithHost:host
                 packageName:@"grpcMobileGatewayService"
                 serviceName:@"grpcMobileGatewayService"
                 callOptions:callOptions];
}

- (instancetype)initWithHost:(NSString *)host {
  return [super initWithHost:host
                 packageName:@"grpcMobileGatewayService"
                 serviceName:@"grpcMobileGatewayService"];
}

#pragma clang diagnostic pop

// Override superclass initializer to disallow different package and service names.
- (instancetype)initWithHost:(NSString *)host
                 packageName:(NSString *)packageName
                 serviceName:(NSString *)serviceName {
  return [self initWithHost:host];
}

- (instancetype)initWithHost:(NSString *)host
                 packageName:(NSString *)packageName
                 serviceName:(NSString *)serviceName
                 callOptions:(GRPCCallOptions *)callOptions {
  return [self initWithHost:host callOptions:callOptions];
}

#pragma mark - Class Methods

+ (instancetype)serviceWithHost:(NSString *)host {
  return [[self alloc] initWithHost:host];
}

+ (instancetype)serviceWithHost:(NSString *)host callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [[self alloc] initWithHost:host callOptions:callOptions];
}

#pragma mark - Method Implementations

#pragma mark HealthCheck(Empty_Request) returns (String_Response)

/**
 * Health check
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)healthCheckWithRequest:(Empty_Request *)request handler:(void(^)(String_Response *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToHealthCheckWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
/**
 * Health check
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToHealthCheckWithRequest:(Empty_Request *)request handler:(void(^)(String_Response *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"HealthCheck"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[String_Response class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
/**
 * Health check
 */
- (GRPCUnaryProtoCall *)healthCheckWithMessage:(Empty_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"HealthCheck"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[String_Response class]];
}

#pragma mark SubcribeEvents(SubcribeEvents_Request) returns (Empty_Response)

/**
 * For refresh: config, caching,..
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)subcribeEventsWithRequest:(SubcribeEvents_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToSubcribeEventsWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
/**
 * For refresh: config, caching,..
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToSubcribeEventsWithRequest:(SubcribeEvents_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"SubcribeEvents"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[Empty_Response class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
/**
 * For refresh: config, caching,..
 */
- (GRPCUnaryProtoCall *)subcribeEventsWithMessage:(SubcribeEvents_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"SubcribeEvents"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[Empty_Response class]];
}

#pragma mark Register(Register_Request) returns (Register_Response)

/**
 * 
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)registerWithRequest:(Register_Request *)request handler:(void(^)(Register_Response *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToRegisterWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
/**
 * 
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToRegisterWithRequest:(Register_Request *)request handler:(void(^)(Register_Response *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"Register"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[Register_Response class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
/**
 * 
 */
- (GRPCUnaryProtoCall *)registerWithMessage:(Register_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"Register"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[Register_Response class]];
}

#pragma mark ActiveAccount(ActiveAccount_Request) returns (ActiveAccount_Response)

/**
 * 
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)activeAccountWithRequest:(ActiveAccount_Request *)request handler:(void(^)(ActiveAccount_Response *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToActiveAccountWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
/**
 * 
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToActiveAccountWithRequest:(ActiveAccount_Request *)request handler:(void(^)(ActiveAccount_Response *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"ActiveAccount"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[ActiveAccount_Response class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
/**
 * 
 */
- (GRPCUnaryProtoCall *)activeAccountWithMessage:(ActiveAccount_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"ActiveAccount"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[ActiveAccount_Response class]];
}

#pragma mark Login(Login_Request) returns (Login_Response)

- (void)loginWithRequest:(Login_Request *)request handler:(void(^)(Login_Response *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToLoginWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
- (GRPCProtoCall *)RPCToLoginWithRequest:(Login_Request *)request handler:(void(^)(Login_Response *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"Login"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[Login_Response class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
- (GRPCUnaryProtoCall *)loginWithMessage:(Login_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"Login"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[Login_Response class]];
}

#pragma mark Logout(Logout_Request) returns (Empty_Response)

- (void)logoutWithRequest:(Logout_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToLogoutWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
- (GRPCProtoCall *)RPCToLogoutWithRequest:(Logout_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"Logout"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[Empty_Response class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
- (GRPCUnaryProtoCall *)logoutWithMessage:(Logout_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"Logout"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[Empty_Response class]];
}

#pragma mark LoginByAccessToken(LoginByAccessToken_Request) returns (LoginByAccessToken_Response)

- (void)loginByAccessTokenWithRequest:(LoginByAccessToken_Request *)request handler:(void(^)(LoginByAccessToken_Response *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToLoginByAccessTokenWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
- (GRPCProtoCall *)RPCToLoginByAccessTokenWithRequest:(LoginByAccessToken_Request *)request handler:(void(^)(LoginByAccessToken_Response *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"LoginByAccessToken"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[LoginByAccessToken_Response class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
- (GRPCUnaryProtoCall *)loginByAccessTokenWithMessage:(LoginByAccessToken_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"LoginByAccessToken"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[LoginByAccessToken_Response class]];
}

#pragma mark LinkAccount(LinkAccount_Request) returns (LinkAccount_Response)

- (void)linkAccountWithRequest:(LinkAccount_Request *)request handler:(void(^)(LinkAccount_Response *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToLinkAccountWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
- (GRPCProtoCall *)RPCToLinkAccountWithRequest:(LinkAccount_Request *)request handler:(void(^)(LinkAccount_Response *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"LinkAccount"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[LinkAccount_Response class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
- (GRPCUnaryProtoCall *)linkAccountWithMessage:(LinkAccount_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"LinkAccount"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[LinkAccount_Response class]];
}

#pragma mark RecoveryPasswordRequest(RecoveryPasswordRequest_Request) returns (RecoveryPasswordRequest_Response)

- (void)recoveryPasswordRequestWithRequest:(RecoveryPasswordRequest_Request *)request handler:(void(^)(RecoveryPasswordRequest_Response *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToRecoveryPasswordRequestWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
- (GRPCProtoCall *)RPCToRecoveryPasswordRequestWithRequest:(RecoveryPasswordRequest_Request *)request handler:(void(^)(RecoveryPasswordRequest_Response *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"RecoveryPasswordRequest"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[RecoveryPasswordRequest_Response class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
- (GRPCUnaryProtoCall *)recoveryPasswordRequestWithMessage:(RecoveryPasswordRequest_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"RecoveryPasswordRequest"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[RecoveryPasswordRequest_Response class]];
}

#pragma mark RecoveryPasswordSubmit(RecoveryPasswordSubmit_Request) returns (Empty_Response)

- (void)recoveryPasswordSubmitWithRequest:(RecoveryPasswordSubmit_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToRecoveryPasswordSubmitWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
- (GRPCProtoCall *)RPCToRecoveryPasswordSubmitWithRequest:(RecoveryPasswordSubmit_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"RecoveryPasswordSubmit"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[Empty_Response class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
- (GRPCUnaryProtoCall *)recoveryPasswordSubmitWithMessage:(RecoveryPasswordSubmit_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"RecoveryPasswordSubmit"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[Empty_Response class]];
}

#pragma mark OpenGameLog(OpenGameLog_Request) returns (Empty_Response)

- (void)openGameLogWithRequest:(OpenGameLog_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToOpenGameLogWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
- (GRPCProtoCall *)RPCToOpenGameLogWithRequest:(OpenGameLog_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"OpenGameLog"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[Empty_Response class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
- (GRPCUnaryProtoCall *)openGameLogWithMessage:(OpenGameLog_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"OpenGameLog"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[Empty_Response class]];
}

#pragma mark InstallGameLog(InstallGameLog_Request) returns (Empty_Response)

- (void)installGameLogWithRequest:(InstallGameLog_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToInstallGameLogWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
- (GRPCProtoCall *)RPCToInstallGameLogWithRequest:(InstallGameLog_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"InstallGameLog"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[Empty_Response class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
- (GRPCUnaryProtoCall *)installGameLogWithMessage:(InstallGameLog_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"InstallGameLog"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[Empty_Response class]];
}

#pragma mark GetProfile(GetProfile_Request) returns (GetProfile_Response)

- (void)getProfileWithRequest:(GetProfile_Request *)request handler:(void(^)(GetProfile_Response *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToGetProfileWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
- (GRPCProtoCall *)RPCToGetProfileWithRequest:(GetProfile_Request *)request handler:(void(^)(GetProfile_Response *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"GetProfile"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[GetProfile_Response class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
- (GRPCUnaryProtoCall *)getProfileWithMessage:(GetProfile_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"GetProfile"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[GetProfile_Response class]];
}

#pragma mark ResendOTP(ResendOTP_Request) returns (ResendOTP_Response)

- (void)resendOTPWithRequest:(ResendOTP_Request *)request handler:(void(^)(ResendOTP_Response *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToResendOTPWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
- (GRPCProtoCall *)RPCToResendOTPWithRequest:(ResendOTP_Request *)request handler:(void(^)(ResendOTP_Response *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"ResendOTP"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[ResendOTP_Response class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
- (GRPCUnaryProtoCall *)resendOTPWithMessage:(ResendOTP_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"ResendOTP"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[ResendOTP_Response class]];
}

#pragma mark SdkInit(SdkInit_Request) returns (SdkInit_Response)

- (void)sdkInitWithRequest:(SdkInit_Request *)request handler:(void(^)(SdkInit_Response *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToSdkInitWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
- (GRPCProtoCall *)RPCToSdkInitWithRequest:(SdkInit_Request *)request handler:(void(^)(SdkInit_Response *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"SdkInit"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[SdkInit_Response class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
- (GRPCUnaryProtoCall *)sdkInitWithMessage:(SdkInit_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"SdkInit"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[SdkInit_Response class]];
}

#pragma mark RequestActive(RequestActive_Request) returns (RequestActive_Response)

- (void)requestActiveWithRequest:(RequestActive_Request *)request handler:(void(^)(RequestActive_Response *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToRequestActiveWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
- (GRPCProtoCall *)RPCToRequestActiveWithRequest:(RequestActive_Request *)request handler:(void(^)(RequestActive_Response *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"RequestActive"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[RequestActive_Response class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
- (GRPCUnaryProtoCall *)requestActiveWithMessage:(RequestActive_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"RequestActive"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[RequestActive_Response class]];
}

#pragma mark IAPInit(IAPInit_Request) returns (IAPInit_Response)

/**
 * 
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)iAPInitWithRequest:(IAPInit_Request *)request handler:(void(^)(IAPInit_Response *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToIAPInitWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
/**
 * 
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToIAPInitWithRequest:(IAPInit_Request *)request handler:(void(^)(IAPInit_Response *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"IAPInit"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[IAPInit_Response class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
/**
 * 
 */
- (GRPCUnaryProtoCall *)iAPInitWithMessage:(IAPInit_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"IAPInit"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[IAPInit_Response class]];
}

#pragma mark FinalizeIAP(FinalizeIAP_Request) returns (Empty_Response)

- (void)finalizeIAPWithRequest:(FinalizeIAP_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToFinalizeIAPWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
- (GRPCProtoCall *)RPCToFinalizeIAPWithRequest:(FinalizeIAP_Request *)request handler:(void(^)(Empty_Response *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"FinalizeIAP"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[Empty_Response class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
- (GRPCUnaryProtoCall *)finalizeIAPWithMessage:(FinalizeIAP_Request *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"FinalizeIAP"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[Empty_Response class]];
}

@end
#endif
